clear all

matconvnetpath = '..\Documents\MATLAB\matconvnet-1.0-beta25';

addpath('trainfunctions');
addpath('initialnetworks');
addpath('utils');
addpath('model-train');

run(fullfile(matconvnetpath, 'matlab', 'vl_setupnn.m'))
addpath(fullfile(matconvnetpath, 'examples'));
%%

trainObjectPose('gpus',[],...
                'expDir', fullfile('experiments','objectPose','tool1'),... % save folder
                'imdbPath','data\tool_yellow.mat',... % image databaseÅ@Å@
                'inNode',3,... % rgb
                'outNode',3,... % angles 
                'batchSize', 40,...
                'numEpochs', 20,...
                'learningRate', 0.1*[0.01*ones(1, 10) 0.005*ones(1, 10) 0.001*ones(1, 10) 0.0005*ones(1, 10) 0.0001*ones(1, 10) 0.00005*ones(1, 10)],...
                'net', 'initializeObjectPoseNet_alexnet_v4',...
                'batchFun', 'getBatch_augment',...
                'derOutputs' , {'objective_angle', 1},...
                'imageSize', [224, 224],...
                'numSubSample', 1);            
