%cd C:\Users\JRLUSER\Documents\MATLAB\pose-detection-object
clear all
addpath('trainfunctions');
addpath('initialnetworks');
addpath('utils');
addpath('model-train');
run(fullfile('C:\Users\yusukey0301\Documents\MATLAB\matconvnet-1.0-beta25', 'matlab', 'vl_setupnn.m'))

%%
trainObjectPose( 'gpus',[],...
                'expDir', fullfile('experiments','objectPose','lipton1'),... % save folder
                'imdbPath','data\lipton.mat',... % image database
                'rotate', 0,...
                'scale',1,...　　　　　　
                'inNode',3,... % rgb
                'outNode',3,... % angles 
                'batchSize', 80,...
                'numEpochs', 40,...
                'learningRate', 0.1*[0.01*ones(1, 10) 0.005*ones(1, 10) 0.001*ones(1, 10) 0.0005*ones(1, 10) 0.0001*ones(1, 10) 0.00005*ones(1, 10)],...
                'transformation', 'none',...
                'net', 'initializeObjectPoseNet_alexnet_v4',...
                'batchFun', 'getBatchDagNNRot_Aug3',...
                'derOutputs' , {'objective_angle', 1},...
                'imageSize', [224, 224],...
                'numSubSample', 1);            
